default:
  aws_access_key_id: 'AKIAIQTGMUFPSGH2YF5A'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'